// gen_graph.cpp
// ---------------------------------------------------------------------------
// Reproducible graph generator for Q6 (connected components).
//
// Emits the Q6 input format on stdout (or to -o FILE):
//     V
//     k v1 v2 ... vk        one line per vertex, i-th line = neighbours of i
//
// Every topology is driven by a fixed --seed, so any dataset can be
// regenerated byte-for-byte from the command line recorded in the README.
//
// Topologies
//   random        E random pairs. With E >> V a single giant component; with
//                 E < V/2, many small ones.
//   path          0-1-2-...-(V-1). Maximum diameter: the adversarial case for
//                 iterative label propagation.
//   shuffled      a path whose vertex IDs are randomly permuted, so block
//                 partitioning no longer matches graph locality. This is the
//                 worst case for the convergence round count.
//   star          one hub joined to all others: severe load imbalance.
//   disconnected  V/2 independent 2-vertex components.
//   isolated      no edges at all (E = 0).
//   cluster       C blobs with no inter-blob edges: known component count.
//   chain-blocks  dense blobs joined in a line by single bridge edges, so
//                 components straddle MPI block boundaries.
//
// --asymmetric writes each edge into only ONE adjacency list, to check that
// both implementations still treat it as undirected.
//
// Build: g++ -O2 -std=c++17 -o gen_graph gen_graph.cpp
// Run  : ./tools/gen_graph -v 1000 -e 5000 -t random -s 42 -o graph.in
// ---------------------------------------------------------------------------

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <numeric>
#include <string>
#include <vector>

// splitmix64: small, fast, and deterministic across platforms, so a given
// seed reproduces the same graph anywhere.
struct Rng {
    uint64_t s;
    explicit Rng(uint64_t seed) : s(seed) {}
    uint64_t next() {
        uint64_t z = (s += 0x9E3779B97F4A7C15ULL);
        z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
        z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
        return z ^ (z >> 31);
    }
    long long below(long long n) { return n <= 0 ? 0 : (long long)(next() % (uint64_t)n); }
};

static void usage(const char* prog) {
    std::fprintf(stderr,
        "usage: %s -v V [-e E] [-t TOPOLOGY] [-s SEED] [-c CLUSTERS]\n"
        "          [--hub H] [--asymmetric] [-o FILE]\n\n"
        "topologies: random path shuffled star disconnected isolated cluster\n"
        "            chain-blocks\n", prog);
}

int main(int argc, char** argv) {
    long long V = -1, E = 0, clusters = 8, hub = 0;
    uint64_t seed = 42;
    std::string topo = "random", outPath = "-";
    bool symmetric = true;

    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        auto need = [&](const char* what) -> const char* {
            if (i + 1 >= argc) { std::fprintf(stderr, "ERROR: %s needs a value\n", what); std::exit(2); }
            return argv[++i];
        };
        if (a == "-v" || a == "--vertices")      V = std::atoll(need("-v"));
        else if (a == "-e" || a == "--edges")    E = std::atoll(need("-e"));
        else if (a == "-t" || a == "--topology") topo = need("-t");
        else if (a == "-s" || a == "--seed")     seed = std::strtoull(need("-s"), nullptr, 10);
        else if (a == "-c" || a == "--clusters") clusters = std::atoll(need("-c"));
        else if (a == "--hub")                   hub = std::atoll(need("--hub"));
        else if (a == "--asymmetric")            symmetric = false;
        else if (a == "-o" || a == "--output")   outPath = need("-o");
        else if (a == "-h" || a == "--help")   { usage(argv[0]); return 0; }
        else { std::fprintf(stderr, "ERROR: unknown option %s\n", a.c_str()); return 2; }
    }
    if (V < 0) { usage(argv[0]); return 2; }

    Rng rng(seed);
    std::vector<std::vector<int>> adj((size_t)V);
    auto add = [&](long long u, long long v) {
        adj[(size_t)u].push_back((int)v);
        if (symmetric) adj[(size_t)v].push_back((int)u);
    };

    if (topo == "random") {
        for (long long i = 0; i < E; i++) {
            long long u = rng.below(V), v = rng.below(V);
            if (u != v) add(u, v);
        }
    } else if (topo == "path") {
        for (long long i = 0; i + 1 < V; i++) add(i, i + 1);
    } else if (topo == "shuffled") {
        std::vector<long long> perm((size_t)V);
        std::iota(perm.begin(), perm.end(), 0LL);
        for (long long i = V - 1; i > 0; i--) std::swap(perm[(size_t)i], perm[(size_t)rng.below(i + 1)]);
        for (long long i = 0; i + 1 < V; i++) add(perm[(size_t)i], perm[(size_t)i + 1]);
    } else if (topo == "star") {
        for (long long i = 0; i < V; i++) if (i != hub) add(hub, i);
    } else if (topo == "disconnected") {
        for (long long i = 0; i + 1 < V; i += 2) add(i, i + 1);
    } else if (topo == "isolated") {
        // no edges
    } else if (topo == "cluster" || topo == "chain-blocks") {
        const long long C = clusters > 0 ? clusters : 1;
        const long long size = V / C;
        for (long long c = 0; c < C; c++) {
            const long long lo = c * size;
            const long long hi = (c == C - 1) ? V : (c + 1) * size;
            if (hi - lo < 2) continue;
            for (long long i = lo; i + 1 < hi; i++) add(i, i + 1);   // spanning path
            const long long extra = (topo == "cluster")
                                        ? (E > 0 ? E / C : (hi - lo))
                                        : (hi - lo) / 2;
            for (long long j = 0; j < extra; j++) {
                long long u = lo + rng.below(hi - lo), v = lo + rng.below(hi - lo);
                if (u != v) add(u, v);
            }
            if (topo == "chain-blocks" && hi < V) add(hi - 1, hi);   // bridge
        }
    } else {
        std::fprintf(stderr, "ERROR: unknown topology '%s'\n", topo.c_str());
        return 2;
    }

    std::string out;
    out.reserve((size_t)V * 8 + 16);
    char tmp[16];
    int len = std::snprintf(tmp, sizeof(tmp), "%lld\n", V);
    out.append(tmp, len);
    for (long long i = 0; i < V; i++) {
        const std::vector<int>& a = adj[(size_t)i];
        len = std::snprintf(tmp, sizeof(tmp), "%zu", a.size());
        out.append(tmp, len);
        for (size_t j = 0; j < a.size(); j++) {
            out.push_back(' ');
            len = std::snprintf(tmp, sizeof(tmp), "%d", a[j]);
            out.append(tmp, len);
        }
        out.push_back('\n');
    }

    if (outPath == "-") {
        std::fwrite(out.data(), 1, out.size(), stdout);
    } else {
        FILE* f = std::fopen(outPath.c_str(), "wb");
        if (!f) { std::fprintf(stderr, "ERROR: cannot write %s\n", outPath.c_str()); return 1; }
        std::fwrite(out.data(), 1, out.size(), f);
        std::fclose(f);
    }
    return 0;
}
